config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get '/' => "home#top"
  post 'reservations/:id' => 'reservations#confirm', as: :confirm_reservation
  get 'home/account' => 'home#account', as: :account_home
  get 'home/profile' => 'home#profile', as: :profile_home
  post 'home/profile' => 'home#update', as: :update_home
  get 'home/area_serch' => 'home#area_serch', as: :area_serch_room
  get 'home/key_serch' => 'home#key_serch', as: :key_serch_room
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :reservations
  devise_for :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def top
    @q = Room.ransack(params[:q])
  end

  def area_serch
    @q = Room.ransack(params[:q])
    @results = @q.result
  end
  
  def key_serch
    @q = Room.ransack(params[:q])
    @results = @q.result 
  end
   
  def account
    @user = current_user
  end

  def profile
    @user = current_user 
  end

  def update
    @user = current_user
    if @user.update(params.permit(:user_image , :username, :self_introduce))
      flash[:notice] = "Profile was successfully updated."
      redirect_to "/"
    else
      render 'profile'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/account.html.erb
<div class="account-container">
    <h4>アカウント</h4>
    <table>
        <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
        </tr>
        <tr>
            <th>パスワード</th>
            <td><%= @user.encrypted_password %>
        </tr>
    </table>
    <a class="edit-btn"  href="/users/edit">編集</a>
</div>

app/views/home/key_serch.html.erb
<h1>検索結果</h1>
<div class="results">
    
    <table>
        <thead class="serch-content">
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>住所</th>
            <th>料金（円)</th>
        </thead>
        <tbody class="serch-infomation">
        <% @results.each do |room| %>
            <tr>
                <td><%= image_tag room.room_image.url, class: "serch-image" %></td>
                <td><%=link_to "#{room.room_name}", controller: 'rooms', action: 'show', id: room.id  %></td>
                <td><%= room.adress %></td>
                <td><%= room.price %></td>
            </tr>
        <% end %>   
        </tbody>    
   </table>    
</div>

app/views/home/profile.html.erb
<% if flash[:notcie] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>
<%= render "shared/partial", obj:@user %>
<div class="profile">
    <div class="profile-form">
        <div class="profile-content">
        <h4>プロフィール</h4>
        <% if @user.user_image? %>
            <%= image_tag @user.user_image.url, class: "login-icon" %>
        <% else %>
            <img class="login-icon" src="/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpeg">
        <% end %>
        </div>

        <div class="profile-container">
            <%= form_with url: update_home_path, method: :post do |f| %>
                <table>
                    <tr>
                        <th><%= f.label :user_image ,"アイコン画像" %></th>
                        <td><%= f.file_field :user_image, value: @user.user_image %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :username ,"名前", class: "username" %></th>
                        <td><%= f.text_field :username, value: @user.username %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :self_introduce ,"自己紹介", class: "self_introduce" %></th>
                        <td><%= f.text_area :self_introduce, value: @user.self_introduce %></td>
                    </tr>
                </table>
                    <ul class="profile-btn-content">
                        <li><%= f.submit "更新", class: "profile-btn"%></li>
                    </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/home/top.html.erb
<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>
<div class="home-content">
    <div class="home-comment">
    </div>
    <img class="home-image" src="/assets/img_cover_top.jpeg">
    <div class="home-serch">
        <p class="home-serch-comment">Potepan Shareで見つける新しい旅</p>
        <div class="home-serch-form">
            <%= search_form_for @q, url: area_serch_room_path do |f| %>
                <%= f.search_field:adress_cont, placeholder: "エリア", class: "home-area-form" %>
                <%= f.submit "探す", class: "home-btn" %>
            <% end %>
        </div>
    </div>
    <div class="area-content">
        <h3>おすすめのエリア</h3>
        <ul class="area-name">
            <li>東京</li>
            <li>大阪</li>
            <li>京都</li>
            <li>札幌</li>
        </ul>
        <div class="area-content-image">
            <%= link_to controller: "home", action: "key_serch", target: "_blank", q: {adress_or_room_name_or_room_introduce_cont: '東京'} do %>
                <img class="area-image" src="/assets/img_tokyo.jpeg">
            <% end %>
            <%= link_to controller: "home", action: "key_serch", target: "_blank", q: {adress_or_room_name_or_room_introduce_cont: '大阪'} do %>
                <img class="area-image" src="/assets/img_osaka.jpeg">
            <% end %>
            <%= link_to controller: "home", action: "key_serch", target: "_blank", q: {adress_or_room_name_or_room_introduce_cont: '京都'} do %>
                <img class="area-image" src="/assets/img_kyoto.jpeg">
            <% end %>
            <%= link_to controller: "home", action: "key_serch", target: "_blank", q: {adress_or_room_name_or_room_introduce_cont: '札幌'} do %>
                <img class="area-image" src="/assets/img_sapporo.jpeg">
            <% end %>
        </div>
    </div>
</div>