config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get '/' => "home#top"
  post 'reservations/:id' => 'reservations#confirm', as: :confirm_reservation
  get 'home/account' => 'home#account', as: :account_home
  get 'home/profile' => 'home#profile', as: :profile_home
  post 'home/profile' => 'home#update', as: :update_home
  get 'home/area_serch' => 'home#area_serch', as: :area_serch_room
  get 'home/key_serch' => 'home#key_serch', as: :key_serch_room
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :reservations
  devise_for :users
end

app/models/room.rb
class Room < ApplicationRecord

    validates :room_name, :room_introduce, :price, :adress, :room_image, presence: true

    mount_uploader :room_image, RoomImageUploader
    
    belongs_to :user
    has_many :reservations

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
        @user = User.find(current_user.id)
        @rooms = @user.rooms
      end
    
      def new
        @room = Room.new
      end
    
      def create
        @room = Room.new(params.require(:room).permit(:room_name, :room_introduce, :price, :adress, :room_image))
        @room.user_id = current_user.id
        if @room.save
          flash[:notice] = "Room was successfully created."
          redirect_to room_path(@room)
        else
          render "new" 
        end
      end
    
      def show
        @room = Room.find(params[:id])
        @reservation = Reservation.new
      end
    
      def edit
      end
    
      def update
      end
    
      def desteroy
      end
      
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="room-post-content">
    <h3>登録済みルーム一覧</h3>
    <table>
        <thead class="room-infomation">
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>料金（円)</th>
            <th>作成日</th>
        </thead>
        <tbody class="room-user-infomation">
        <% @rooms.each do |room| %>
            <tr>
                <td><%= image_tag room.room_image.url, class: "image" %></td>
                <td><%=link_to "#{room.room_name}", controller: 'rooms', action: 'show', id: room.id  %></td>
                <td><%= room.room_introduce %></td>
                <td><%= room.price %></td>
                <td><%= room.created_at.to_s %></td>
            </tr>
        <% end %>    
        </tbody>    
   </table>
</div>

app/views/rooms/new.html.erb
<div class ="room-new">
<h3>ルーム情報登録</h3>

<%= render "shared/partial", obj:@room %>
    <div class="room-new-form"> 
        <%= form_with model: @room do |f| %>
            <table>
                <tr>
                    <th><%= f.label :room_name ,"ルーム名", class: "room_name" %></th>
                    <td><%= f.text_field :room_name %></td>
                </tr>
        
                <tr>
                    <th><%= f.label :room_introduce ,"ルーム紹介", class: "room_introduce" %></th>
                    <td><%= f.text_field :room_introduce, placeholder: "ルーム説明を入力" %></td>
                </tr>
        
                <tr>
                    <th><%= f.label :price ,"料金", class: "price" %></th>
                    <td><%= f.number_field :price, placeholder: "1日あたりの料金" %></td>
                </tr>
        
                <tr>
                    <th><%= f.label :adress ,"住所", class: "adress" %></th>
                    <td><%= f.text_area :adress %></td>
                </tr>

                <tr>
                    <th><%= f.label :room_image ,"ルーム画像", class: "room_image" %>
                    <td><%= f.file_field :room_image %></td>
                </tr>
            </table>
        
            <div>
                <ul class="room-btn-content">
                    <li><%= f.submit "登録完了する"%></li>
                </ul>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/show.html.erb
<% if flash[:notcie] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>
<%= render "shared/partial", obj:@reservation %>

<div class="room-show-content">
    <div class="room-show-name">
    <%= @room.room_name %>
    </div>
    <%= image_tag @room.room_image.url, class: "show-image" %>
    <div class="resservations-form">
        <%= form_with url: confirm_reservation_path do |f| %>
        <table>
            <tr>
                <th><%= f.label :startDay, "開始日", class: "startDay" %></th>
                <td><%= f.date_field :startDay %></td>
            </tr>
            <tr>
                <th><%= f.label :endDay, "終了日", class: "endDay" %></th>
                <td><%= f.date_field :endDay %></td>
            </tr>
            <tr>
                <th><%= f.label :numberOfPeople, "人数", class: "numberOfPeople" %></th>
                <td><%= f.number_field :numberOfPeople %></td>
            </tr>
            <%= f.hidden_field :room_id, value: @room.id %>
        </table>
 
        <ul>
            <li><%= f.submit "予約する", {class: "yoyaku"} %></li>
        </ul>
        <% end %>    
    </div>
</div>